#+TITLE: Devuan GNU+Linux
#+OPTIONS: toc:nil num:nil html-postamble:nil
#+STARTUP: showall

* Partitioning

- EFI  32M
- LVM
  + swap 512M or 1G
  + /    rest

** 32G
#+begin_src example
# fdisk -l /dev/sde
Disk /dev/sde: 28.65 GiB, 30765219840 bytes, 60088320 sectors
Disk model:  SanDisk 3.2Gen1
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: B6F02B81-1546-5D47-9602-E58072BC378F

Device     Start      End  Sectors  Size Type
/dev/sde1   2048    67583    65536   32M EFI System
/dev/sde2  67584 60086271 60018688 28.6G Linux filesystem
#+end_src
** 64G
#+begin_src example
# fdisk -l /dev/sde
Disk /dev/sde: 57.3 GiB, 61524148224 bytes, 120164352 sectors
Disk model:  SanDisk 3.2Gen1
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 022FBF37-4FAA-DB49-A0FC-7DE4201EFD62

Device     Start       End   Sectors  Size Type
/dev/sde1   2048     67583     65536   32M EFI System
/dev/sde2  67584 120162303 120094720 57.3G Linux filesystem
#+end_src

* Encrypted LVM
#+begin_src bash
  cryptsetup luksFormat --type luks1 /dev/sde2
  cryptsetup luksOpen /dev/sde2 root1vm
  vgcreate root1vm /dev/mapper/root1vm
  lvcreate --name swap -L 512M root1vm
  lvcreate --name root -l 100%FREE root1vm
  mkfs.vfat -n EFI1 /dev/sde1
  mkfs.ext4 -L ROOT1 /dev/root1vm/root
  mkswap -L SWAP1 /dev/root1vm/swap

  mkdir /mnt/debinst
  mount /dev/root1vm/root /mnt/debinst/
  swapon /dev/root1vm/swap

  mkdir -p /mnt/debinst/boot/efi
  mount /dev/sde1 /mnt/debinst/boot/efi/
#+end_src

** 32G
#+begin_src example
# lsblk -f /dev/sde
NAME               FSTYPE  FSVER  LABEL UUID                                   FSAVAIL FSUSE% MOUNTPOINTS
sde
├─sde1             vfat    FAT16  EFI1  AED6-BD65                                31.9M     0% /mnt/debinst/boot/efi
└─sde2             crypto_ 1            16645700-2da1-4512-bb00-e6b7f4b39714
  └─root1vm        LVM2_me LVM2 0       znR4uZ-ZWcZ-E1cT-A30U-nUHS-3lfY-L0Xuv6
    ├─root1vm-swap swap    1      SWAP1 fb2ec4c3-6bfd-4111-bfb2-0fb12ed04e5f                  [SWAP]
    └─root1vm-root ext4    1.0    ROOT1 52526ed9-4087-4141-9351-c121b9d329ba     12.5G     3% /mnt/debinst
#+end_src
** 64G
#+begin_example
# lsblk -f /dev/sde
NAME            FSTYPE FSVER LABEL UUID                                   FSAVAIL FSUSE% MOUNTPOINTS
sde
├─sde1          vfat   FAT16 EFI7  06F0-045B                                31.9M     0% /mnt/debinst/boot/efi
└─sde2          crypto 1           a1741189-00dc-4d77-a463-28ca6f49e9bf
  └─root7vm     LVM2_m LVM2        balDce-MQmx-0iCm-Lic0-GBUN-SxZf-YJQTy9
    ├─root7vm-swap
    │           swap   1     SWAP7 467752f4-2bf9-4d6e-a24d-286ac60e256a                  [SWAP]
    └─root7vm-root
                ext4   1.0   ROOT7 e71b6cd8-d34b-4020-a45c-f3387fac5b38     52.2G     0% /mnt/debinst
#+end_example

* Debootstrap

#+begin_src bash
  debootstrap --arch=amd64 --merged-usr --include=mc,tmux,zile,bash-completion,net-tools,lvm2,cryptsetup,cryptsetup-initramfs,console-setup,fonts-terminus daedalus /mnt/debinst http://deb.devuan.org/merged
#+end_src

#+begin_src bash
  cp Work/devuan/root/.bash_profile /mnt/debinst/root
  cp Work/devuan/root/.bashrc /mnt/debinst/root
  cp Work/devuan/root/.inputrc /mnt/debinst/root
  cp Work/devuan/root/.tmux.conf /mnt/debinst/root
  cp Work/devuan/etc/apt/sources.list /mnt/debinst/etc/apt
  cp Work/devuan/etc/apt/apt.conf.d/90norecommends /mnt/debinst/etc/apt/apt.conf.d
  cp Work/devuan/etc/network/interfaces /mnt/debinst/etc/network
#+end_src

#+begin_src bash
  LANG=C.UTF-8 bin/xchroot /mnt/debinst /bin/bash
  export TERM=xterm-color
  printf '\e]0;%s\a' "Devuan CHROOT"
#+end_src
or
#+begin_src bash
  mount -t proc  none     /mnt/debinst/proc
  mount -t sysfs none     /mnt/debinst/sys
  mount --rbind  /dev     /mnt/debinst/dev
  mount --rbind  /run     /mnt/debinst/run
  LANG=C.UTF-8 chroot /mnt/debinst /bin/bash
  export TERM=xterm-color
  printf '\e]0;%s\a' "Devuan CHROOT"
#+end_src

#+begin_src bash
  apt install openssh-server openssh-client gawk mawk- locales man-db manpages manpages-dev pciutils file traceroute mime-support lsof curl wget plocate nmap ncat bc psmisc git silversearcher-ag gcc libc6-dev libc-devtools fortune-mod fortunes fortunes-debian-hints flex bison aptitude debootstrap gpm chrony ncal evtest ripgrep htop ckermit tio deborphan apt-rdepends rpm sqlite3 lsb-release zstd unzip daemon dosfstools eject rsync fakeroot
#+end_src

#+begin_src bash
  apt install --install-recommends imagemagick
#+end_src
#+begin_example
The following additional packages will be installed:
  imagemagick-6.q16 libdjvulibre-text libdjvulibre21 libmagickcore-6.q16-6-extra
  libnetpbm11 netpbm
#+end_example

* Kernel
#+begin_src bash
  apt install linux-image-amd64 linux-headers-amd64 intel-microcode amd64-microcode firmware-linux-free firmware-linux-nonfree firmware-realtek
#+end_src

#+begin_src bash
  dpkg-reconfigure debconf
  dpkg-reconfigure keyboard-configuration
  dpkg-reconfigure locales
  dpkg-reconfigure console-setup
  dpkg-reconfigure tzdata
#+end_src

* LUKS key
#+begin_src bash
  dd bs=1 count=64 if=/dev/urandom of=/boot/volume.key
  cryptsetup luksAddKey /dev/sde2 /boot/volume.key
  chmod 000 /boot/volume.key
  chmod -R g-rwx,o-rwx /boot
#+end_src

* GRUB
#+begin_src bash
  apt install grub-efi --install-recommends
#+end_src

#+begin_src bash
  grub-install --removable --recheck --efi-directory=/boot/efi --boot-directory=/boot /dev/sde
  update-grub
  update-initramfs -u
#+end_src

* Dotfiles (duplicated?)
- /root/.bash_profile
- /root/.bashrc
- /root/.inputrc
- /root/.tmux.conf
- /etc/apt/sources.list
- /etc/network/interfaces
- /etc/hostname
- /etc/hosts
- /etc/fstab
- /boot/volume.key
- /etc/crypttab
- /etc/default/grub
- /etc/cryptsetup-initramfs/conf-hook
- /boot/grub/background.tga
- /boot/grub/splash.tga
- /boot/grub/terminus28b.pf2

* crypttab

* fstab

* Openbox
#+begin_src bash
  apt install openbox obconf xorg xinit xterm xtermcontrol rxvt-unicode lxappearance gmrun barrier xdotool wmctrl picom xclip adwaita-icon-theme gnome-themes-extra suckless-tools xbindkeys xcape x11-utils feh qiv xdg-utils xdg-user-dirs xdg-desktop-portal-gtk pipewire-audio xserver-xorg-video-intel xserver-xorg-video-radeon va-driver-all vdpau-driver-all mesa-vulkan-drivers fonts-open-sans fonts-inconsolata fonts-dejavu fonts-hack fonts-liberation geany pavucontrol pulseaudio-utils pulsemixer pamixer neofetch cmus cmus-plugin-ffmpeg gkrellm gkrellm-volume dict rofi dunst tint2 firefox-esr ca-certificates libpaper-utils catdoc ffmpeg parcellite librsvg2-common
#+end_src

* KDE Stuff
#+begin_src bash
  apt install qt5ct breeze breeze-gtk-theme breeze-icon-theme dolphin filelight kate kompare kpat ktorrent okteta okular kde-spectacle kdegraphics-thumbnailers dolphin-plugins kio-extras libmtp-runtime polkit-kde-agent-1 pkexec kruler kcolorchooser
#+end_src

* MPV
#+begin_src bash
  apt install -t daedalus-backports mpv yt-dlp
#+end_src

* Emacs
#+begin_src bash
  apt install -t daedalus-backports emacs-gtk emacs-common-non-dfsg
  apt install autoconf automake gcc libpng-dev libpoppler-dev libpoppler-glib-dev libz-dev make pkg-config cmake libtool libvterm-dev
#+end_src

* Office
#+begin_src bash
  apt install -t daedalus-backports libreoffice-writer libreoffice-calc libreoffice-math libreoffice-gtk3 libreoffice-style-breeze hunspell-en-us hunspell-pt-br hunspell
#+end_src

* obmenu-generator
#+begin_src bash
  apt install perl libdata-dump-perl libgtk3-perl cpanminus
  cpanm Linux::DesktopFiles
#+end_src

#+begin_src bash
  mkdir ~/.config/obmenu-generator
  ln -s ../../Work/dotfiles/obmenu-generator/schema.pl ~/.config/obmenu-generator
  ln -s ../Work/dotfiles/bin/obmenu-generator ~/bin/
#+end_src

* Connman
#+begin_src bash
  apt install connman-gtk connman connman-vpn wpasupplicant
#+end_src

* ESP-IDF
#+begin_src bash
  apt install git wget flex bison gperf python3 python3-dev python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
  apt install python3-serial
#+end_src

* Distrobox
#+begin_src bash
  apt install podman --install-recommends
#+end_src

#+begin_src bash
  distrobox create --image docker.io/library/ubuntu:16.04 --name ubuntu16
  distrobox list
  distrobox enter ubuntu16
  distrobox stop ubuntu16
  distrobox rm ubuntu16
#+end_src

#+begin_src bash
  dpkg --add-architecture i386
  apt update
  apt upgrade
  apt-get --no-install-recommends install bash-completion file git mg mc tmux rxvt-unicode-256color xterm xtermcontrol man-db manpages manpages-dev locales psmisc patch rsync ssh-client shared-mime-info xdg-user-dirs mime-support unzip netbase rename ttf-dejavu
  apt install eagle
#+end_src

* Install printer (Brother HL-1212W)
#+begin_src bash
  apt install cups cups-filters cups-ipp-utils cups-pk-helper printer-driver-brlaser system-config-printer ghostscript
  usermod -a -G lp,lpadmin lefty
#+end_src
As normal user:
#+begin_src bash
  system-config-printer
#+end_src
- Unlock
- Add
  + Network Printer
    - Find Network Printer
    - Host: printer ip <- Find
      + IPP Printer <- Forward
        - Brother (recommended) <- Forward
          + HL-1200 (recommended) <- Forward
    - Describe Printer <- Apply

* To buku or not to buku
#+begin_src bash
  apt install buku python3-lxml
#+end_src

* Stuff
#+begin_src bash
  apt install dosbox calibre inkscape qalc
  apt install gimp --install-recommends
  apt install openvpn openresolv --install-recommends
#+end_src

* WTF
** Stranger Things
- apparmor                                 purge
- arch-test                                purge
- evemu-tools                              purge
  + libevemu3                              purge
- libpng-tools                             purge
- libsasl2-modules                         purge
- mpv recommends pocketsphinx-en-us        purge
- wget recommends publicsuffix             purge
- lvm2 recommends thin-provisioning-tools  purge
- seatd                                    uninstalled
- libltdl-dev                              purge?
- libldap-common                           purge
- libfl2                                   purge?
- libfl-dev                                purge?
- libfile-fcntllock-perl                   purge build-essential
- libdecor-0-plugin-1-cairo                purged
- libc-devtools                            manual
- build-essentials depends dpkg-dev        purged
  + dpkg-dev recommends or pulls           purged
    - libalgorithm-diff-perl               purged
    - libalgorithm-diff-xs-perl            purged
    - libalgorithm-merge-perl              purged
- mpv depends libbluray2
  + libbluray2 recommends libaacs0         purged
    - libaacs0 depends libbdplus0          purged
- Imagemagick recommends                   --install-recommends
  + libdjvulibre21
  + libdjvulibre-text
  + libmagickcore-6.q16-6-extra
  + libnetpbm11
  + netpbm

** Why?
- /sbin/resolvconf: 230: /lib/resolvconf/libc: cannot create /etc/resolv.conf: Directory nonexistent
- At boot, before asking the encryption password
  + "error: no such device: /.disk/info."
  + "error: no such device: /.disk/mini-info."
  + dumb "solution": copy /boot/efi/EFI/BOOT to /boot/efi/EFI/debian

* The Whole Enchilada
#+begin_src bash
  bin/packages-list
#+end_src
- [[file:packages.all-manual.txt][All Manually installed packages]]
- [[file:packages.all-auto.txt][All Automatically installed packages]]
- [[file:packages.all.txt][All installed packages]]
- [[file:packages.nbp-manual.txt][Non Backports Manually installed packages]]
- [[file:packages.nbp-auto.txt][Non Backports Automatically installed packages]]
- [[file:packages.bp-manual.txt][Backports Manually installed packages]]
- [[file:packages.bp-auto.txt][Backports Automatically installed packages]]

* Foreign partitions
: mount UUID=bed5cbc3-3d88-4091-b687-96679440b6c0 /mnt/Energos/
: mount UUID=a63767c2-0ab6-469b-a39d-f8db4a2ca1e0 /mnt/Depot/
: mount UUID=eb6403a3-a0fb-47b7-a68f-7bf38b57894b /mnt/Depot2/
